base16:
    filename: colors/{{ scheme-system }}-{{ scheme-slug }}.vim
    supported-systems: [base16]

base24:
    filename: colors/{{ scheme-system }}-{{ scheme-slug }}.vim
    supported-systems: [base24]
