name: Check that building template does not produce additional changes
on:
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the repository code
        uses: actions/checkout@v4
      - name: Update schemes
        uses: tinted-theming/tinted-builder-rust@latest
      - name: Check if there are changes
        run: git diff --exit-code
